[package]
name = "use_surreal"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
surrealdb = "2.0.4"
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["rt-multi-thread", "macros"] }
