version: "3"

services:
  surrealdb:
    env_file:
      - .env
    image: surrealdb/surrealdb:latest
    container_name: $CONTAINER_NAME
    restart: always
    # command: start -A --auth --user root --pass root file:/database.db
    entrypoint:
      - /surreal
      - start
      - -A
      - --auth
      - --user
      - $DB_USER
      - --pass
      - $DB_PASS
      - file:/database.db
    ports:
      - $DB_PORT:8000

    volumes:
      - ./database/database.db:/database.db
