services:
  surrealdb:
    env_file:
      - .env
    image: surrealdb/surrealdb:latest
    container_name: $CONTAINER_NAME
    restart: always
    # command: start -A --auth --user root --pass root file:/database.db
    entrypoint:
      - /surreal
      - start
      - -A
      - --user
      - $DB_USER
      - --pass
      - $DB_PASS
      - surrealkv:/data/${DB_NAME}
    ports:
      - $DB_PORT:8000
    volumes:
      - volume:/data
volumes:
  volume:
    name: ${DB_PATH}
    external: true
